ollama_image_analysis:
  name: Analyze camera image with local AI based upon Ollama
  description: Analyze a camera image with a local AI model (e.g. llava) based upon Ollama
  fields:
    prompt:
      description: The prompt describing how to analyze the image
      example: |
        You are a security agent and analyze the following camera image. Your focus is to identify irregularities. Please list all irregularities.
      required: true
      selector:
        text:
          multiline: true
    image_paths:
      description: This should be the paths or a direct urls to a snapshot images taken from your camera which shall be analyzed.
      example: 
        - /x/y/camera_image.jpg 
        - http://www.google.com/images/camera_image.jpg
      required: true
      selector:
        object:
    model:
      description: Choose which model to use. Defaults to llava.
      example: llava
      default: llava
      required: false
      selector:
        text:
